-- Apply once in the Supabase SQL editor.
alter table public.trip_schedule add column if not exists rejection_reason text;
alter table public.trip_schedule add column if not exists expiry_reason text;
alter table public.maintenance_log add column if not exists target_date date;

create table if not exists public.schedule_blackout (
  blackout_id bigint generated by default as identity primary key,
  blackout_date date not null unique,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_schedule_blackout_date
  on public.schedule_blackout (blackout_date);

create table if not exists public.attendance_record (
  attendance_id bigint generated by default as identity primary key,
  employee_name text not null,
  employee_id text,
  pay_period text,
  day_label text,
  work_date date,
  raw_date text,
  time_in text,
  time_out text,
  work_time text,
  daily_total text,
  note text,
  source_file text,
  raw_payload jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_attendance_record_import_identity
  on public.attendance_record (
    source_file,
    employee_name,
    work_date,
    time_in,
    time_out
  );

create index if not exists idx_attendance_record_work_date
  on public.attendance_record (work_date desc);
