-- Apply once in the Supabase SQL editor.
alter table public.trip_schedule add column if not exists rejection_reason text;
alter table public.trip_schedule add column if not exists expiry_reason text;
alter table public.maintenance_log add column if not exists target_date date;

create table if not exists public.schedule_blackout (
  blackout_id bigint generated by default as identity primary key,
  blackout_date date not null unique,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_schedule_blackout_date
  on public.schedule_blackout (blackout_date);