-- Add a human-facing incremental staff number without changing the UUID
-- ownership key used by trip_schedule and authentication.
begin;

alter table public.user_account
  add column if not exists staff_number bigint generated by default as identity;

create unique index if not exists user_account_staff_number_key
  on public.user_account (staff_number);

commit;
